### PR TITLE
FlattenMapper integration improvements + minor refactoring

### PR DESCRIPTION
**Pull request by anisimovyuriy**
Dear @JonPSmith,

I created PR for your PR :) - just some improvements integration plus refactoring. Could you please review it? When you merge to your branch - I'll do the merge to Expressmapper.

Gratefully Yours,
Yuriy

### CODE REVIEW

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy,

OK, that is much better. I see you have moved Flattening inside `CompileInternal` which where it should be. I took the approach of minimal changes to ExpressMapper because I didn't want to break anything. Your changes are so right.

I my only comment is I think the name `FlattenSource` is a better name, as it makes it clear that it only flattenes the source and doesn't do an un-flatten on the destination (someone wanted un-flatten in your ExpressMapper [issue 85](https://github.com/expressmapper/ExpressMapper/issues/86)). If you are happy then I will change `Flatten` back to `FlattenSource`. Let me know.

I'll merge the PR and do some checking, especially around nested mapping and let you know.

**Comment by anisimovyuriy** [comment]
Dear @JonPSmith,

Thanks a lot for your review. The main reason I renamed it `.Flatten()` - just to make names as short as possible (one word) - I kind of stick to this rule :). But definitely go ahead and rename it if you think it might bring more clarity.

Thank you @JonPSmith  for your great job!

**Comment by JonPSmith** [comment]
Hi @anisimovyuriy,

PR merged. Added a few more tests for nesting mappings. I kept the short name of `Flatten()` as it fits your style. I'll start on the documentation in the ExpressMapper Wiki sometime soon.

Let me know when you might release this as I plan to write a long article on [my blog site](http://www.thereformedprogrammer.net/) about Entity Framework and flattening SQL relationships.

**Comment by ant-github** [comment]
Hi JonPSmith,

I am using ExpressMapper in my project.it was working well before i integrated Dependency Injection.
As i integrate DI.ExpressMapper throw  an exception. If i remove Mapping then its working well.

Geeting this error 
Additional information: Error error occured trying to compile mapping for: source VotingTool.Data.Models.Event, destination VotingTool.Domain.Models.EventModel. See the inner exception for details.   

{"No parameterless constructor defined for this object."}

**Comment by JonPSmith** [comment]
Hi @ant-github,

I'm not the real expert on ExpressMapper as @anisimovyuriy is. However the error `{"No parameterless constructor defined for this object."}` sounds like a problem in your DI set up, not ExpressMapper . It is most likely caused by either `VotingTool.Data.Models.Event` or `VotingTool.Domain.Models.EventModel` not having a parameterless constructor.

**Pull request merged**
